/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Danilo' at '11/30/16 1:53 AM' with Gradle 2.14.1
 *
 * @author danilo, @date 11/30/16 1:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
